import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import React, {createContext, Dispatch, ReactNode, useContext, useEffect, useState} from 'react';
import { selectedLang } from '../Components/functions';

i18n
  .use(initReactI18next)
  .init({
    resources: {
      en: {
        translation: {
          welcome: "Welcome to our application",
          home : "Home",
          productType : "Product type",
          productSettings: 'Product settings',
          shoes : "Shoes",
          sandals : 'Sandals',
          shirts : 'Shirts',
          pants :'Pants',
          Shoes : "Shoes",
          Sandals : 'Sandals',
          Shirts : 'Shirts',
          Pants :'Pants',
          YourCart : 'Your cart',
          ourPromotions : 'Our offers and promotions',
          ourProducts : 'Our products',
          viewProduct : 'View the product',
          addCart : 'Add to cart',
          soldOut : 'Sold out',
          sizes:'Sizes',
          price:'Price',
          mad  : 'MAD',
          next : 'Next',
          previous : 'Previous',
          productPreview : 'Product preview',
          productInfos : 'Product infos',
          quantitAction : 'Quantity/Action',
          total:'Total',
          clearCart : 'Clear cart',
          orderSummary : 'ORDER SUMMARY',
          shipping : 'Shipping',
          other : 'Other',
          size : 'Size',
          totalAmount : 'Total amount',
          removeItem : 'Are you sure you want to remove this item ?',
          deleteConf : 'Delete confirmation ',
          category : 'Category',
          ref : 'Ref',
          name : 'Name',
          before : 'Before',
          remove : 'Remove',
          cancelBack : 'Cancel and Back',
          removeAll : 'Are you sure you want to remove all the items ?',
          clearAllItems : 'Clear all items',
          shopNow : 'Shop now',
          nullCart: 'There are no items in your shopping cart',
          promotion : 'Discount',
          off : 'Off',
          toastSizeAlert : 'Size is not selected !',
          toastAddSuccess : 'A new shoe item is added !',
          toCart : "To cart",
          clientInfos : 'Client informations',
          paymentPortal : 'Payment portal',
          checkoutAlert : 'Fill the form firstly, then choose the payment method 👍🏻',
          creditCard : 'Credit card',
          firstN :'First name',
          lastN : 'Last name',
          fullName: ' Full name',
          email : 'E-mail',
          phN : 'Phone number',
          address : 'Address',
          city : 'City',
          save : 'Save',
          saveMod : 'Save modifications',
          modify:'Modify',
          pay:'Pay',
          loading : 'Loading . . .',
          yourOrder : 'Your order',
          transactionInfos : 'Transaction infos',
          code : 'Code',
          currency : 'Currency',
          amount : 'Amount',
          orderId : 'Order ID',
          transactionId : 'Transaction ID',
          successMsg : 'Your transaction is successfully completed',
          downloadTicket : 'Download e-command ticket',
          readMore : 'Read more',
          readLess : 'Read less',
          quantity : 'Quantity',
          thank : 'Thank you for your confidence',
          menu : 'Menu',
          fnreq : 'Your first name is required',
          lnreq : ' Your last name is required',
          emlreq : 'Your e-mail is required',
          telreq : 'Your phone number is required',
          cityreq : 'Your city is required',
          addressreq : 'Your address is required',
          goShoesSec :'Go to shoes section',
          goSandalsSec :'Go to sandals section',
          goShirtsSec :'Go to shirts section',
          goPantsSec :'Go to pants section',
          directCmd : 'Checkout now !',
          shoesPlus :'More shoes',
          sandalsPlus:'More sandals',
          shirtsPlus:'More shirts',
          pantsPlus:'More pants',
          details:'Details',
          delivery:'Delivery',
          free : 'Free',
          deliveryTime:'Delivery time',
          payments:'Payments',
          expectedTime: 'expected',
          from:'from',
          to:'to',
          productReviews : 'Product reviews',          
          addReview : 'Add your review',
          addMyReview:'Add the review',
          stars:'Stars',
          username:'Username',
          yourReview:'Your review',
          firstReview:'Put the first review !',
          cod: 'Cash on delivery COD',
          choosePM : 'Please choose a payment method !',
          choicePM: 'Chosen payment method',
          noChoicePM : 'Not chosen yet !',
          signOut :'Sign out',
          orders : 'Orders',
          deficiencies : 'Quantity\'s deficiency',
          loadingProducts : 'Products are loading...',
          stayTuned : 'Stay tuned !',
          productsComing : 'New products will come !',
          settings: 'Settings',
          statistics : 'Statistics',
          remainingOrders: 'Remaining orders',
          deliveredOrders : 'Delivered orders',
          allOrders: 'All orders',
          back : 'Back',
          extractDeliveryForm: 'Extract delivery form',

        },
      },
      fr: {
        translation: {
          welcome: "Bienvenue dans notre application",
          productType : "Type de produit",
          productSettings : 'paramètres du produit',
          home : "Accueil",
          shoes : "Shoes",
          sandals : 'Sandales',
          shirts : 'Shirts',
          pants :'Pants',
          Shoes : "Shoes",
          Sandals : 'Sandales',
          Shirts : 'Shirts',
          Pants :'Pants',
          YourCart : 'Votre panier',
          ourPromotions : 'Nos offres et promotions',
          ourProducts : 'Nos produits',
          viewProduct : 'Voir le produit',
          addCart : 'Ajouter au panier',
          soldOut : 'Epuisé',
          sizes : 'Tailles',
          price : 'Prix',
          mad : 'MAD',
          next : 'Suivant',
          previous : 'Précédant',
          productPreview : 'Aperçu du produit',
          productInfos : 'Infos du produit',
          quantitAction : 'Quantité/Action',
          total:'Total',
          clearCart : 'Vider le panier',
          orderSummary : 'La commande',
          shipping : 'Transport',
          other : 'Autre',
          size : 'Taille',
          totalAmount : 'Montant ',
          removeItem : 'Etes-vous sûr de vouloir supprimer cet élément ?',
          deleteConf : 'Confirmation de supression',
          category : 'Catégorie',
          ref : 'Ref',
          name : 'Nom',
          before : 'Avant',
          remove : 'Supprimer',
          cancelBack : 'Annuler et revenir',
          removeAll : 'Etes-vous sûr de vouloir supprimer tous les éléments ?',
          clearAllItems : 'Effacer tous',
          shopNow : 'Achetez maintenant',
          nullCart: 'Il n\'y a aucun article dans votre panier',
          promotion : 'Promotion',
          off : 'Moins',
          toastSizeAlert : "La taille n'est pas choisie !",
          toastAddSuccess : "Une nouvelle chaussure est ajoutée !",
          toCart : "Retour au panier",
          clientInfos : 'Informations du client',
          paymentPortal : 'Portail de paiement',
          checkoutAlert : "Remplissez d'abord le formulaire, puis choisissez le mode de paiement 👍🏻",
          creditCard : 'Carte bancaire',
          firstN :'Prénom',
          lastN : 'Nom',
          fullName: 'Nom et prénom',
          email : 'E-mail',
          phN : 'N° de téléphone',
          address : 'Adresse',
          city : 'Ville',
          save : 'Sauvegarder',
          saveMod : 'Sauvegarder les modifications',
          modify:'Modifier',
          pay : 'Payer',
          loading : 'Chargement . . .',
          yourOrder : 'Votre commande',
          transactionInfos : 'Infos de transaction',
          code : 'code',
          currency : 'Devise',
          amount : 'Montant',
          orderId : 'ID commande',
          transactionId : 'ID transaction',
          successMsg : 'Votre transaction est effectuée avec succès',
          downloadTicket : 'Télécharger le ticket de l\'e-commande',
          readMore : 'Lire plus',
          readLess : 'Lire moins',
          quantity : 'Quantité',
          thank : 'Merci pour votre confiance !',
          menu : 'Menu',
          fnreq : 'Votre prénom est obligatoire',
          lnreq : ' Votre nom est obligatoire',
          emlreq : 'Votre e-mail est obligatoire',
          telreq : 'Votre N° téléphone est obligatoire',
          cityreq : 'Votre ville est obligatoire',
          addressreq : 'Votre adresse est obligatoire',
          goShoesSec :'Aller à la section des chaussures',
          goSandalsSec :'Aller à la section des sandales',
          goShirtsSec :'Aller à la section des chemises',
          goPantsSec :'Aller à la section des pantalons',
          directCmd : 'Checkout maintenant !',
          shoesPlus :'Plus de chaussures',
          sandalsPlus:'Plus de sandales',
          shirtsPlus:'Plus de shirts',
          pantsPlus:'Plus pants',
          details:'Détails',
          delivery:'Livraison',
          free : 'Free',
          deliveryTime:'Délai de livraison',
          payments:'Paiements',
          expectedTime: 'attendu',
          from:'de',
          to:'à',
          productReviews : ' Avis sur les produits',
          addReview : 'Ajouter votre avis',
          addMyReview:'Ajouer l\'avis',
          stars:'Etoiles',
          username:'Nom d\'utilisateur',
          yourReview:'votre avis',
          firstReview:'Publier le premier avis !',
          cod: 'Cash on delivery COD',
          choosePM : 'Merci de choisir une métode de paiment!',
          choicePM: 'Méthode de paiment choisie',
          noChoicePM : 'Pas encore choisi !',
          signOut :'Déconnexion',
          orders : 'Ordres',
          deficiencies : 'Déficit de quantité',
          loadingProducts : 'Chargement des produits...',
          stayTuned : 'Restez à l\'écoute !',
          productsComing : 'De nouveaux produits arriveront !',
          settings: 'Paramètres',
          statistics:'Statistiques',
          remainingOrders: 'Commandes en attente',
          deliveredOrders : 'Commandes livrées',
          allOrders: 'Toutes les commandes',       
          back : 'Retour',   
          extractDeliveryForm: 'استخراج نموذج التسليم',


        },
      },
      ar: {
        translation: {
          welcome: "مرحبًا بك في تطبيقنا",
          home : "الرئيسية",
          productType : "نوع المنتج",
          productSettings : 'إعدادات المنتج',
          shoes : "الاحذية",
          sandals : 'صنادل',
          shirts : 'اقمصة',
          pants :'سراويل',
          Shoes : "الاحذية",
          Sandals : 'صنادل',
          Shirts : 'اقمصة',
          Pants :'سراويل',
          YourCart : 'السلة',
          ourPromotions : 'العروض و التخفيضات',
          ourProducts : 'منتوجاتنا',
          viewProduct : 'معاينة المنتج',
          addCart : 'اضافة الى السلة',
          soldOut : 'نفذ',
          sizes : 'المقاسات',
          price : 'السعر',
          mad : "د.م",
          next : 'التالي',
          previous : 'السابق',
          productPreview : 'معاينة المنتج',
          productInfos : 'تفاصيل المنتج',
          quantitAction : 'الكمية/اجراء',
          total:'المجموع',
          clearCart : 'افراغ السلة',
          orderSummary : 'ملخص الطلبية',
          shipping : 'النقل',
          other : 'اخرى',
          size : 'المقاس',
          totalAmount : 'المبلغ الاجمالي',
          removeItem : 'هل أنت متأكد أنك تريد إزالة هذا العنصر؟',
          deleteConf : 'تاكيد الحذف',
          category : 'الصنف',
          ref : 'المرجع',
          name : 'الاسم',
          before : 'قبل',
          remove : 'حذف',
          cancelBack : 'الالغاء و العودة',
          removeAll : 'هل أنت متأكد أنك تريد حذف كافة العناصر؟',
          clearAllItems : 'حذف الكل',
          shopNow : 'تسوق الآن',
          nullCart: 'لا يوجد أي سلع في سلة التسوق الخاصة بك',
          promotion : 'عرض خاص',
          off : 'تخفيض',
          toastSizeAlert : "! لم يتم اختيار مقاس محدد",
          toastAddSuccess : "! تمت اضافة عنصر جديد الى السلة ",
          toCart : "الرجوع الى السلة",
          // For checkout page
          clientInfos : 'معلومات الزبون',
          paymentPortal : 'بوابة الدفع',
          checkoutAlert : "  قم أولاً بملء نموذج الدفع، ثم اختر طريقة الدفع 👍🏻",
          creditCard : 'بطاقة بنكية',
          firstN :'الاسم',
          lastN : 'النسب',
          fullName: 'الاسم الكامل',
          email : 'البريد الالكتروني',
          phN : 'رقم الهاتف',
          address : 'العنوان',
          city : 'المدينة',
          save : 'حفظ',
          saveMod : 'حفظ التغييرات',
          modify:'تعديل',
          pay : 'دفع',
          loading : '. . . جاري التحميل ',
          // For transaction details
          yourOrder : 'طلبيتكم',
          transactionInfos : 'معلومات التحويل',
          code : 'الرمز',
          currency : 'العملة',
          amount : 'المبلغ',
          orderId : 'معرف الطلبية',
          transactionId : 'معرف التحويل',
          successMsg : 'اكتملت معاملتك بنجاح',
          downloadTicket : 'تنزيل تذكرة الطلبية',
          readMore : 'رؤية الكل',
          readLess : 'رؤية اقل',
          quantity : 'الكمية',
          thank : '!شكرا على ثقتكم',
          menu : 'القائمة',
          // For client form
          fnreq : 'اسمك مطلوب',
          lnreq : 'الاسم النسب مطلوب',
          emlreq : 'بريدكم الإلكتروني مطلوب',
          telreq : 'رقم هاتفكم مطلوب',
          cityreq : 'اسم مدينتكم مطلوب',
          addressreq : 'عنوانكم مطلوب',
          // For home page links
          goShoesSec :'الذهاب إلى قسم الأحذية',
          goSandalsSec :'الذهاب إلى قسم الصنادل',
          goShirtsSec :'الذهاب إلى قسم القمصان',
          goPantsSec :' الذهاب إلى قسم السراويل',
          directCmd : '! الدفع الآن',
          // For success trans page
          shoesPlus :'المزيد من الأحذية',
          sandalsPlus:'المزيد من الصنادل',
          shirtsPlus:'المزيد من القمصان',
          pantsPlus:'المزيد من السراويل',
          // For product page details
          details:'التفاصيل',
          delivery:'التوصيل',
          free : 'مجاني',
          deliveryTime:'موعد التسليم',
          payments:'طرق الدفع',
          expectedTime: 'المتوقع',
          from:'من',
          to:'الى',
          //For product category details
          productReviews : 'مراجعات المنتج',
          addReview : 'إضافة مراجعة',
          addMyReview:'اضافة المراجعة',
          stars:'التقييم',
          username:'اسم المستخدم',
          yourReview:'تعليقك',
          firstReview : '! نشر المراجعة الأولى',
          cod: 'COD الدفع عند الاستلام ',
          choosePM : '! المرجو اختيار طريقة الدفع',
          choicePM: 'طريقة الدفع المختارة',
          noChoicePM: 'لم يتم اختياره بعد!',
          signOut :'تسجيل الخروج',
          orders : 'الطلبيات',
          deficiencies : 'نقص الكميات',
          loadingProducts : 'جاري تحميل المنتجات...',
          stayTuned : '! ترقبوا',
          productsComing : '! منتجات جديدة قادمة',
          settings: 'لاعدادات',
          statistics:'الاحصائيات',
          remainingOrders: 'طلبيات في انتظار التاكيد',
          deliveredOrders : 'الطلبيات المُسلّمة',
          allOrders: 'جميع الطلبيات',
          back: 'الرجوع',
          extractDeliveryForm: 'استخراج نموذج التسليم',
          
       
       
        },

      },
    },
    lng: "fr",
    fallbackLng: "en",
    interpolation: {
      escapeValue: false, 
    },
  });

  interface langContextProps{
    currentLang : string;
    setCurrentLang : Dispatch<React.SetStateAction<string>>
  }
  
  const langContext = createContext<langContextProps | undefined>(undefined);
  export const LangContextProvider : React.FC<{children:ReactNode}> = ({children}) =>{
    const [currentLang, setCurrentLang] = useState<string>(()=>{
      const lang = sessionStorage.getItem('AlFirdaousStoreLang');
      if(lang){return JSON.parse(lang)}else{
        return "English"
      }
    });
    useEffect(()=>{
      sessionStorage.setItem('AlFirdaousStoreLang', JSON.stringify(currentLang));
      i18n.changeLanguage(selectedLang(currentLang));
    },[currentLang])


    return(
        <langContext.Provider value={{currentLang, setCurrentLang}}>
            {children}
        </langContext.Provider>
    )
  };

export default i18n;
export const useLangContext = () : langContextProps => {
    const context = useContext(langContext);
    if(context===undefined){
        throw new Error('useLangContext must be used within a langContextProvider');
    }
    return context
}